language: shell
install: true
os:
  - linux
  - osx
  - windows

before_script:
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh; fi
  - bash .travis/install_jdk.sh

script:
  - java --version