language: shell
install: true
os:
  - linux
  - osx
  - windows

compiler:
  - gcc

matrix:
  include:
    - os: windows
      before_script:
        - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
        - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
        - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
        - cmd.exe /C '.\.travis\install-zlib.bat' || cat install.log
      install: choco install mingw
      script:
        - mingw32-make pkg-windows
    - os: linux
      before_script:
        - sudo add-apt-repository -y ppa:saiarcot895/myppa
        - sudo apt update
        - sudo apt install openjdk-8-jdk zlib1g zlib1g-dev
      script:
        - make pkg-linux
    - os: osx
      before_script:
        - brew tap AdoptOpenJDK/openjdk
        - brew cask install adoptopenjdk8
        - brew install zlib
      script:
        - make pkg-macos