language: shell
install: true
os:
  - linux
  - osx
  - windows

compiler:
  - gcc

matrix:
  include:
    - os: windows
      before_script:
        - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
        - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
        - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
        - export CC=gcc
        - export CXX=g++
        - wget https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3.exe
        - cmd.exe /C 'zlib-1.2.3.exe /SP /SILENT'
      script:
        - mingw32-make -f windows.Makefile
    - os: linux
      before_script:
        - sudo add-apt-repository -y ppa:saiarcot895/myppa
        - sudo apt update
        - sudo apt install openjdk-8-jdk zlib1g zlib1g-dev
      script:
        - make -f linux.Makefile
    - os: osx
      before_script:
        - brew tap AdoptOpenJDK/openjdk
        - brew cask install adoptopenjdk8
        - brew install zlib
      script:
        - make -f macos.Makefile

notifications:
  email: false
